/*
homework = [
        {
        name: '',
        description: '',
        dueDate: '',
        class: '',
        completed: false,
        }
    ]
*/

let homework = localStorage.getItem('homework');

if (homework) {
    homework = JSON.parse(homework);
} else {
    homework = [];
}

//function generated by copilot
function formatDateTime(datetimeLocalValue) {
    const date = new Date(datetimeLocalValue);

    const options = { month: '2-digit', day: '2-digit', year: 'numeric' };
    const formattedDate = date.toLocaleDateString('en-US', options);

    let hours = date.getHours();
    const minutes = date.getMinutes().toString().padStart(2, '0');
    const ampm = hours >= 12 ? 'PM' : 'AM';
    hours = hours % 12 || 12;

    const formattedTime = `${hours}:${minutes} ${ampm}`;

    return ` ${formattedTime} - ${formattedDate}`;
}

function homeworkPopup() {
    const popup = document.getElementById('homework-popup');
    popup.style.display = 'flex';
    document.getElementById('popup-bg').style.display = 'block';
    //i love copilot
    const dueDateInput = document.getElementById("homework-due-date");
    if (dueDateInput) {
        const now = new Date();
        const offset = now.getTimezoneOffset() * 60000; // Offset in milliseconds
        const localDateTime = new Date(now.getTime() - offset); // Adjust to local time
        const formattedDateTime = localDateTime.toISOString().slice(0, 16); // Format to 'YYYY-MM-DDTHH:mm'
        dueDateInput.value = formattedDateTime;
    }
}

function addHomework() {
    const homeworkName = document.getElementById('homework-name').value;
    const homeworkDescription = document.getElementById('homework-description').value;
    const homeworkDueDate = document.getElementById('homework-due-date').value;
    const homeworkClass = document.getElementById('homework-class').value;

    const newHomework = {
        name: homeworkName,
        description: homeworkDescription,
        dueDate: homeworkDueDate,
        class: homeworkClass,
        completed: false,
    };
    homework.push(newHomework);

    localStorage.setItem('homework', JSON.stringify(homework));

    displayHomework();
    document.getElementById('homework-popup').style.display = 'none';
    document.getElementById('popup-bg').style.display = 'none';
}

function displayHomework() {
    const homeworkList = document.getElementById('homework-container');
    homeworkList.innerHTML = '';
    if (homework.length === 0) {
        homeworkList.innerHTML = '<h1 style="text-align: center;">No homework assigned.</h1>';
    } else {
        for (let i = 0; i < homework.length; i++) {
            const homeworkItem = homework[i];
            const listItem = document.createElement('div');
            listItem.innerHTML = `<button>&#10003;</button> <strong class="hw-name">${homeworkItem.name}</strong> <p class="hw-desc">${homeworkItem.description}</p> <p class="hw-dueDate">${formatDateTime(homeworkItem.dueDate)}</p> <p class="hw-subject">${homeworkItem.class}</p>`;
            homeworkList.appendChild(listItem);
        }
    }
}

function removeHomework(index) {
    homework.splice(index, 1);
    localStorage.setItem('homework', JSON.stringify(homework));
    displayHomework();
}

document.getElementById('add-homework-button').addEventListener('click', homeworkPopup);

document.getElementById('cancel-homework-button').addEventListener('click', () => {
    document.getElementById('homework-popup').style.display = 'none';
    document.getElementById('popup-bg').style.display = 'none';
});

document.getElementById('popup-bg').addEventListener('click', () => {
    document.getElementById('homework-popup').style.display = 'none';
    document.getElementById('popup-bg').style.display = 'none';
});

document.getElementById('save-homework-button').addEventListener('click', addHomework);

//function generated by copilot
document.getElementById('homework-container').addEventListener('click', (event) => {
    if (event.target.tagName === 'BUTTON') {
        const index = Array.from(event.target.parentNode.parentNode.children).indexOf(event.target.parentNode);
        removeHomework(index);
    }
});

displayHomework();
